apiVersion: v2
name: ai-gateway
description: Runtime-brandable OpenAI-compatible AI gateway for AWS Bedrock
type: application
version: 0.1.5
appVersion: "sha-780e85ea932bc12a38fe5abe8f963f31ad3cda37"
home: https://github.com/ricsam/ai-gateway
sources:
  - https://github.com/ricsam/ai-gateway
maintainers:
  - name: ricsam
    url: https://github.com/ricsam
