import { useMemo, useState } from "react";
import { IconArrowDown, IconArrowUp } from "@tabler/icons-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";
type Dir = "asc" | "desc";
function SortButton({ active, direction, children, onClick }: { active: boolean; direction: Dir; children: React.ReactNode; onClick: () => void }) { return <button className="inline-flex items-center gap-1" onClick={onClick}>{children}{active && (direction === "asc" ? <IconArrowUp size={14} /> : <IconArrowDown size={14} />)}</button> }
export interface UserSummaryRow { userId: string; username: string; creditsUsed: number; activeDays: number; avgCreditsPerDay: number; lastActivity: string | null; percentOfTotal: number }
export function UserSummaryTable({ users, isLoading }: { users: UserSummaryRow[]; isLoading?: boolean }) { const [sort, setSort] = useState<"creditsUsed" | "activeDays" | "avgCreditsPerDay">("creditsUsed"); const [direction, setDirection] = useState<Dir>("desc"); const rows = useMemo(() => [...users].sort((a, b) => (direction === "asc" ? 1 : -1) * (a[sort] - b[sort])), [users, sort, direction]); const click = (key: typeof sort) => { if (key === sort) setDirection(direction === "asc" ? "desc" : "asc"); else { setSort(key); setDirection("desc"); } }; if (isLoading) return <Skeleton className="h-40" />; if (!users.length) return <p className="py-10 text-center text-sm text-muted-foreground">No user data available</p>; const credits = users.reduce((sum, row) => sum + row.creditsUsed, 0); return <Table><TableHeader><TableRow><TableHead>User</TableHead><TableHead className="text-right"><SortButton active={sort === "creditsUsed"} direction={direction} onClick={() => click("creditsUsed")}>Credits</SortButton></TableHead><TableHead className="text-right"><SortButton active={sort === "activeDays"} direction={direction} onClick={() => click("activeDays")}>Active days</SortButton></TableHead><TableHead className="text-right"><SortButton active={sort === "avgCreditsPerDay"} direction={direction} onClick={() => click("avgCreditsPerDay")}>Avg/day</SortButton></TableHead><TableHead className="text-right">Last activity</TableHead><TableHead className="text-right">% total</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.userId}><TableCell className="font-mono">{row.username}</TableCell><TableCell className="text-right">${row.creditsUsed.toFixed(2)}</TableCell><TableCell className="text-right">{row.activeDays}</TableCell><TableCell className="text-right">${row.avgCreditsPerDay.toFixed(2)}</TableCell><TableCell className="text-right">{row.lastActivity ? new Date(row.lastActivity).toLocaleDateString() : "—"}</TableCell><TableCell className="text-right">{row.percentOfTotal.toFixed(1)}%</TableCell></TableRow>)}</TableBody><TableFooter><TableRow><TableCell>Total</TableCell><TableCell className="text-right">${credits.toFixed(2)}</TableCell><TableCell colSpan={3} /><TableCell className="text-right">100%</TableCell></TableRow></TableFooter></Table> }
export interface GroupSummaryRow { groupId: string; groupName: string; creditsUsed: number; activeUsers: number; avgCreditsPerUser: number }
export function GroupSummaryTable({ groups, isLoading }: { groups: GroupSummaryRow[]; isLoading?: boolean }) { const [sort, setSort] = useState<keyof Pick<GroupSummaryRow, "creditsUsed" | "activeUsers" | "avgCreditsPerUser">>("creditsUsed"); const rows = useMemo(() => [...groups].sort((a, b) => b[sort] - a[sort]), [groups, sort]); if (isLoading) return <Skeleton className="h-40" />; if (!groups.length) return <p className="py-10 text-center text-sm text-muted-foreground">No group data available</p>; const credits = groups.reduce((sum, row) => sum + row.creditsUsed, 0); return <Table><TableHeader><TableRow><TableHead>Group</TableHead><TableHead className="cursor-pointer text-right" onClick={() => setSort("creditsUsed")}>Credits</TableHead><TableHead className="cursor-pointer text-right" onClick={() => setSort("activeUsers")}>Active users</TableHead><TableHead className="cursor-pointer text-right" onClick={() => setSort("avgCreditsPerUser")}>Avg/user</TableHead></TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.groupId}><TableCell>{row.groupName}</TableCell><TableCell className="text-right">${row.creditsUsed.toFixed(2)}</TableCell><TableCell className="text-right">{row.activeUsers}</TableCell><TableCell className="text-right">${row.avgCreditsPerUser.toFixed(2)}</TableCell></TableRow>)}</TableBody><TableFooter><TableRow><TableCell>Total</TableCell><TableCell className="text-right">${credits.toFixed(2)}</TableCell><TableCell colSpan={2} /></TableRow></TableFooter></Table> }
