import { useMemo } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ReferenceLine, XAxis, YAxis } from "recharts";
import { ChartContainer, ChartLegend, ChartLegendContent, ChartTooltip, ChartTooltipContent, type ChartConfig } from "@/components/ui/chart";
import { Skeleton } from "@/components/ui/skeleton";
import type { TimeRange } from "./analytics-controls";
export const formatCurrency = (value: number) => `$${value.toFixed(2)}`;
export const formatTokenCount = (value: number) => value >= 1_000_000 ? `${(value / 1_000_000).toFixed(1)}M` : value >= 1_000 ? `${(value / 1_000).toFixed(1)}K` : String(value);
function stamp(value: string, range: TimeRange) { const date = new Date(value); return range === "hour" || range === "day" ? date.toLocaleTimeString(undefined, { hour: "2-digit", minute: "2-digit" }) : date.toLocaleDateString(undefined, { month: "short", day: "numeric", ...(range === "year" ? { year: "2-digit" } : {}) }); }
function Empty({ loading }: { loading?: boolean }) { return loading ? <Skeleton className="h-[250px] w-full" /> : <div className="grid h-[250px] place-items-center text-sm text-muted-foreground">No data available</div> }
const money: ChartConfig = { value: { label: "Credits", color: "var(--chart-1)" } };
export function BalanceBurndownChart({ data, currentBalance, timeRange = "month", isLoading }: { data: { time: string; balance: number }[]; currentBalance: number; timeRange?: TimeRange; isLoading?: boolean }) { if (isLoading || !data.length) return <Empty loading={isLoading} />; return <ChartContainer config={{ balance: money.value! }} className="h-[250px] w-full"><LineChart data={data}><CartesianGrid vertical={false} /><XAxis dataKey="time" tickFormatter={(v) => stamp(v, timeRange)} /><YAxis tickFormatter={(v) => `$${v}`} width={55} /><ChartTooltip content={<ChartTooltipContent formatter={(v: unknown) => formatCurrency(Number(v))} labelFormatter={(v: unknown) => stamp(String(v), timeRange)} />} /><ReferenceLine y={currentBalance} stroke="currentColor" strokeDasharray="4 4" /><Line dataKey="balance" stroke="var(--color-balance)" dot={false} strokeWidth={2} /></LineChart></ChartContainer> }
export function CreditsConsumedChart({ data, timeRange = "month", isLoading }: { data: { time: string; consumed: number }[]; timeRange?: TimeRange; isLoading?: boolean }) { if (isLoading || !data.length) return <Empty loading={isLoading} />; return <ChartContainer config={{ consumed: { label: "Consumed", color: "var(--chart-1)" } }} className="h-[250px] w-full"><BarChart data={data}><CartesianGrid vertical={false} /><XAxis dataKey="time" tickFormatter={(v) => stamp(v, timeRange)} /><YAxis tickFormatter={(v) => `$${v}`} width={55} /><ChartTooltip content={<ChartTooltipContent formatter={(v: unknown) => formatCurrency(Number(v))} labelFormatter={(v: unknown) => stamp(String(v), timeRange)} />} /><Bar dataKey="consumed" fill="var(--color-consumed)" /></BarChart></ChartContainer> }
const tokenConfig: ChartConfig = { inputTokens: { label: "Input", color: "var(--chart-1)" }, outputTokens: { label: "Output", color: "var(--chart-2)" }, cacheReadTokens: { label: "Cache read", color: "var(--chart-3)" }, cacheWrite5mTokens: { label: "Cache write 5m", color: "var(--chart-4)" }, cacheWrite1hTokens: { label: "Cache write 1h", color: "var(--chart-5)" } };
export function TokensConsumedChart({ data, timeRange = "month", isLoading }: { data: Array<{ time: string; inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWrite5mTokens: number; cacheWrite1hTokens: number }>; timeRange?: TimeRange; isLoading?: boolean }) { if (isLoading || !data.length) return <Empty loading={isLoading} />; return <ChartContainer config={tokenConfig} className="h-[250px] w-full"><BarChart data={data}><CartesianGrid vertical={false} /><XAxis dataKey="time" tickFormatter={(v) => stamp(v, timeRange)} /><YAxis tickFormatter={formatTokenCount} width={55} /><ChartTooltip content={<ChartTooltipContent formatter={(v: unknown) => formatTokenCount(Number(v))} labelFormatter={(v: unknown) => stamp(String(v), timeRange)} />} /><ChartLegend content={<ChartLegendContent />} />{Object.keys(tokenConfig).map((key) => <Bar key={key} dataKey={key} stackId="tokens" fill={`var(--color-${key})`} />)}</BarChart></ChartContainer> }
const colors = ["var(--chart-1)", "var(--chart-2)", "var(--chart-3)", "var(--chart-4)", "var(--chart-5)"];
function MultiLine({ series, rows, timeRange, loading, valueLabel }: { series: string[]; rows: Array<{ time: string; name: string; value: number }>; timeRange: TimeRange; loading?: boolean; valueLabel: "currency" | "balance" }) { const config = useMemo(() => Object.fromEntries(series.map((name, i) => [name, { label: name, color: colors[i % colors.length] }])), [series]); const data = useMemo(() => { const map = new Map<string, Record<string, string | number>>(); for (const row of rows) { const item = map.get(row.time) ?? { time: row.time }; item[row.name] = row.value; map.set(row.time, item); } return [...map.values()].map((item) => { for (const name of series) item[name] ??= 0; return item; }); }, [rows, series]); if (loading || !data.length) return <Empty loading={loading} />; return <ChartContainer config={config} className="h-[250px] w-full"><LineChart data={data}><CartesianGrid vertical={false} /><XAxis dataKey="time" tickFormatter={(v) => stamp(v, timeRange)} /><YAxis tickFormatter={(v) => `$${v}`} width={55} /><ChartTooltip content={<ChartTooltipContent formatter={(v: unknown) => valueLabel === "currency" ? formatCurrency(Number(v)) : formatCurrency(Number(v))} labelFormatter={(v: unknown) => stamp(String(v), timeRange)} />} /><ChartLegend content={<ChartLegendContent />} />{series.map((name, i) => <Line key={name} dataKey={name} stroke={colors[i % colors.length]} dot={false} strokeWidth={2} />)}</LineChart></ChartContainer> }
export function UsageByModelChart({ data, models, timeRange = "month", isLoading }: { data: { time: string; model: string; consumed: number }[]; models: string[]; timeRange?: TimeRange; isLoading?: boolean }) { return <MultiLine rows={data.map((row) => ({ time: row.time, name: row.model, value: row.consumed }))} series={models} timeRange={timeRange} loading={isLoading} valueLabel="currency" /> }
export function GroupUserBurndownChart({ users, timeRange = "month", isLoading }: { users: Array<{ userId: string; username: string; data: { time: string; balance: number }[] }>; timeRange?: TimeRange; isLoading?: boolean }) { return <MultiLine rows={users.flatMap((user) => user.data.map((row) => ({ time: row.time, name: user.username, value: row.balance })))} series={users.map((user) => user.username)} timeRange={timeRange} loading={isLoading} valueLabel="balance" /> }
