import { useMemo, useState } from "react";
import { IconArrowDown, IconArrowUp, IconArrowsSort } from "@tabler/icons-react";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "@/components/ui/table";
export interface ModelAnalyticsRow { model: string; totalCredits: number; inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWrite5mTokens: number; cacheWrite1hTokens: number; percentOfTotal: number }
type Key = keyof ModelAnalyticsRow;
const columns: Array<{ key: Key; label: string; format: (row: ModelAnalyticsRow) => string }> = [
  { key: "model", label: "Model", format: (r) => r.model }, { key: "totalCredits", label: "Credits", format: (r) => `$${r.totalCredits.toFixed(4)}` },
  { key: "inputTokens", label: "Input", format: (r) => r.inputTokens.toLocaleString() }, { key: "outputTokens", label: "Output", format: (r) => r.outputTokens.toLocaleString() },
  { key: "cacheReadTokens", label: "Cache read", format: (r) => r.cacheReadTokens.toLocaleString() }, { key: "cacheWrite5mTokens", label: "Cache 5m", format: (r) => r.cacheWrite5mTokens.toLocaleString() },
  { key: "cacheWrite1hTokens", label: "Cache 1h", format: (r) => r.cacheWrite1hTokens.toLocaleString() }, { key: "percentOfTotal", label: "% total", format: (r) => `${r.percentOfTotal.toFixed(1)}%` },
];
export function ModelDeepDiveTable({ models, isLoading }: { models: ModelAnalyticsRow[]; isLoading?: boolean }) { const [sort, setSort] = useState<Key>("totalCredits"); const [asc, setAsc] = useState(false); const rows = useMemo(() => [...models].sort((a, b) => { const av = a[sort], bv = b[sort]; const value = typeof av === "string" ? av.localeCompare(String(bv)) : Number(av) - Number(bv); return asc ? value : -value }), [models, sort, asc]); const total = useMemo(() => ({ model: "Total", totalCredits: models.reduce((s, r) => s + r.totalCredits, 0), inputTokens: models.reduce((s, r) => s + r.inputTokens, 0), outputTokens: models.reduce((s, r) => s + r.outputTokens, 0), cacheReadTokens: models.reduce((s, r) => s + r.cacheReadTokens, 0), cacheWrite5mTokens: models.reduce((s, r) => s + r.cacheWrite5mTokens, 0), cacheWrite1hTokens: models.reduce((s, r) => s + r.cacheWrite1hTokens, 0), percentOfTotal: models.length ? 100 : 0 }), [models]); if (isLoading) return <Skeleton className="h-40" />; if (!models.length) return <p className="py-10 text-center text-sm text-muted-foreground">No usage data</p>; return <Table><TableHeader><TableRow>{columns.map((column) => <TableHead key={column.key} className={column.key === "model" ? "cursor-pointer" : "cursor-pointer text-right"} onClick={() => { if (sort === column.key) setAsc(!asc); else { setSort(column.key); setAsc(false); } }}>{column.label}{sort === column.key ? (asc ? <IconArrowUp className="inline" size={14} /> : <IconArrowDown className="inline" size={14} />) : <IconArrowsSort className="inline opacity-30" size={14} />}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row) => <TableRow key={row.model}>{columns.map((column) => <TableCell key={column.key} className={column.key === "model" ? "font-mono" : "text-right font-mono tabular-nums"}>{column.format(row)}</TableCell>)}</TableRow>)}</TableBody><TableFooter><TableRow>{columns.map((column) => <TableCell key={column.key} className={column.key === "model" ? "font-semibold" : "text-right font-mono font-semibold"}>{column.format(total)}</TableCell>)}</TableRow></TableFooter></Table> }
